### PR TITLE
Replace string values with numerical tokens in zipcodes.json

### PR DESCRIPTION
**Pull request by mojtabamehrara**
This reduced the json file size from 1.3 MB down to 660 KBs, at the expense of an extra hash look up.

### CODE REVIEW

**Comment by benbuckman** [comment]
Yes please, it's a waste of memory to duplicate the same strings over and over.

**Comment by frenchie4111** [comment]
Great change! Merging.

**Comment by mojtabamehrara** [comment]
Thanks @frenchie4111 !

**Comment by benbuckman** [comment]
@frenchie4111 Can you push a new NPM release with these changes?
Thank you

**Pull request merged**
